// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaaenzixvevbtjdvaykd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhYWVueml4dmV2YnRqZHZheWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODk4NzMsImV4cCI6MjA1Nzg2NTg3M30.lnG0SpOLCIPzfzaqHsqCJ5TOlKGXCbUra9RI2ty28mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);